// ----------------------------------------------------------------------

export const paths = {
  // Services
  services: {
    root: '/tilaa-sankari',
    airConditioning: '/ilmastointityot',
    asbestos: '/asbestikartoitus',
    cleaningHome: '/koti-siivoukset',
    cleaningMoving: '/muuttosiivous',
    cleaningOffice: '/yrityssiivous-toimistosiivous',
    cleaningRenovation: '/siivouspalvelut',
    cleaningWindow: '/ikkunanpesu',
    delivery: '/kuljetuspalvelut',
    domesticHelp: '/kotiapu',
    electrician: '/sahkoasennukset',
    electronicAppliance: '/elektroniikkahuolto',
    handyman: '/asennuspalvelut',
    homeAppliance: '/kodinkonehuolto',
    movingLifting: '/kantoapu',
    movingService: '/muutto',
    plumber: '/putkityot',
    propertyMaintenance: '/kiinteistohuolto',
    refrigerationAppliance: '/kylmalaitteiden-asennus',
    renovation: '/remontti',
    yardModification: '/piha-rakentaminen',
    yardWork: '/pihatyot',
    openOrder: '/koti-palvelu',
  },
  // Marketing
  marketing: {
    root: '/marketing',
    services: '/marketing/services',
    caseStudies: '/marketing/case-studies',
    caseStudy: `/marketing/case-study`,
    posts: '/marketing/posts',
    post: `/marketing/post`,
    about: '/marketing/about',
    contact: '/marketing/contact',
  },
  // Travel
  travel: {
    root: '/travel',
    tours: '/travel/tours',
    tour: `/travel/tour`,
    checkout: '/travel/checkout',
    orderCompleted: '/travel/order-completed',
    posts: '/travel/posts',
    post: `/travel/post`,
    about: '/travel/about',
    contact: '/travel/contact',
  },
  // Career
  career: {
    root: '/career',
    jobs: '/career/jobs',
    job: `/career/job`,
    posts: '/career/posts',
    post: `/career/post`,
    about: '/career/about',
    contact: '/career/contact',
  },
  // E-learning
  eLearning: {
    root: '/e-learning',
    courses: '/e-learning/courses',
    course: `/e-learning/course`,
    posts: '/e-learning/posts',
    post: `/e-learning/post`,
    about: '/e-learning/about',
    contact: '/e-learning/contact',
  },
  // E-commerce
  eCommerce: {
    root: '/e-commerce',
    products: '/e-commerce/products',
    product: `/e-commerce/product`,
    cart: '/e-commerce/cart',
    checkout: `/e-commerce/checkout`,
    orderCompleted: '/e-commerce/order-completed',
    wishlist: `/e-commerce/wishlist`,
    compare: `/e-commerce/compare`,
    account: {
      root: `/e-commerce/account`,
      personal: `/e-commerce/account/personal`,
      wishlist: `/e-commerce/account/wishlist`,
      vouchers: `/e-commerce/account/vouchers`,
      orders: `/e-commerce/account/orders`,
      payment: `/e-commerce/account/payment`,
    },
  },
  // Blogs
  blogs: {
    root: '/blogs',
    blog: {
      blog1: `/blogs/blog1`,
      blog2: `/blogs/blog2`,
      blog3: `/blogs/blog3`,
    },
  },
  // Auth
  loginCover: '/auth/login-cover',
  loginBackground: '/auth/login-background',
  loginIllustration: '/auth/login-illustration',
  registerCover: '/auth/register-cover',
  registerBackground: '/auth/register-background',
  registerIllustration: '/auth/register-illustration',
  forgotPassword: '/auth/forgot-password',
  verify: '/auth/verify',
  // Common
  offerRequestSent: '/offer-request-sent',
  maintenance: '/maintenance',
  comingsoon: '/coming-soon',
  pricing01: '/pricing-01',
  pricing02: '/pricing-02',
  payment: '/payment',
  support: '/support',
  page404: '/error/404',
  page500: '/error/500',
  // Components
  components: {
    root: '/components',
    animate: '/components/animate',
    carousel: '/components/carousel',
    countUp: '/components/count-up',
    form: '/components/form-validation',
    icons: '/components/icons',
    image: '/components/image',
    label: '/components/label',
    lightbox: '/components/lightbox',
    markdown: '/components/markdown',
    megaMenu: '/components/mega-menu',
    navigation: '/components/navigation-bar',
    scroll: '/components/scroll',
    scrollProgress: '/components/scroll-progress',
    player: '/components/player',
    textMaxLine: '/components/text-max-line',
  },

  // Others
  pages: '/pages',
  joinHero24: '/liity-sankariksi',
  contact: '/yhteystiedot',
  docs: 'https://zone-docs.vercel.app',
  license: 'https://material-ui.com/store/license/#i-standard-license',
  minimalStore: 'https://material-ui.com/store/items/minimal-dashboard',
  zoneStore: 'https://mui.com/store/items/zone-landing-page/',
  figmaPreview:
    'https://www.figma.com/file/Zam9QBLhV4pZf5xtNs0Lf8/%5BPreview%5D-Zone_Web.v2.3.0?type=design&node-id=59%3A680507&mode=design&t=GCVeJci5zfUu5WCy-1',
  appStoreLink: 'https://apps.apple.com/us/app/hero24/id1642167956',
  googlePlayLink:
    'https://play.google.com/store/apps/details?id=com.hero24.app&hl=en',
};
