export type IServiceProps = {
  id: string;
  slug: string;
  slugKey: string;
  serviceSlug: string;
  price: number;
  heroUrl: string;
  createdAt: Date;
  coverUrl: string;
  location: string;
  duration: string;
  continent: string;
  priceSale: number;
  gallery1: string[];
  gallery2: string[];
  gallery3: string[];
  gallery4: string[];
  gallery5: string[];
  gallery6: string[];
  gallery7: string[];
  gallery8: string[];
  gallery9: string[];
  gallery10: string[];
  gallery11: string[];
  gallery12: string[];
  gallery13: string[];
  gallery14: string[];
  gallery15: string[];
  gallery16: string[];
  gallery17: string[];
  gallery18: string[];
  gallery19: string[];
  gallery20: string[];
  gallery21: string[];
  gallery22: string[];
  favorited: boolean;
  services: string[];
  description: string;
  languages: string[];
  ratingNumber: number;
  highlights1: string;
  highlights2: string;
  highlights3: string;
  reasons1: string;
  reasons2: string;
  reasons3: string;
  stripePaymentLink1: { value: string; label: string }[];
  stripePaymentLink2: { value: string; label: string }[];
  stripePaymentLink3: { value: string; label: string }[];
  stripePaymentLink4: { value: string; label: string }[];
  stripePaymentLink5: { value: string; label: string }[];
  stripePaymentLink6: { value: string; label: string }[];
  stripePaymentLink7: { value: string; label: string }[];
  stripePaymentLink8: { value: string; label: string }[];
  stripePaymentLink9: { value: string; label: string }[];
  stripePaymentLink10: { value: string; label: string }[];
  stripePaymentLink11: { value: string; label: string }[];
  stripePaymentLink12: { value: string; label: string }[];
  stripePaymentLink13: { value: string; label: string }[];
  stripePaymentLink14: { value: string; label: string }[];
  stripePaymentLink15: { value: string; label: string }[];
  stripePaymentLink16: { value: string; label: string }[];
  stripePaymentLink17: { value: string; label: string }[];
  stripePaymentLink18: { value: string; label: string }[];
  stripePaymentLink19: { value: string; label: string }[];
  stripePaymentLink20: { value: string; label: string }[];
  stripePaymentLink21: { value: string; label: string }[];
  stripePaymentLink22: { value: string; label: string }[];
  available: {
    start: Date;
    end: Date;
  };
  program: {
    label: string;
    text: string;
  }[];
};
