// ----------------------------------------------------------------------

export const _id = [...Array(40)].map(
  (_, index) => `e99f09a7-dd88-49d5-b1c8-1daf80c2d7b${index + 1}`
);

// ----------------------------------------------------------------------

export const _booleans = [
  true,
  true,
  true,
  false,
  false,
  true,
  false,
  false,
  false,
  false,
  true,
  true,
  true,
  false,
  false,
  false,
  true,
  false,
  false,
  false,
  true,
  false,
  false,
  true,
];

// ----------------------------------------------------------------------

export const _citiesFinlandArea1 = [
  'Helsinki',
  'Espoo',
  'Vantaa',
  'Kauniainen',
  'Porvoo',
  'Lohja',
  'Hyvinkää',
  'Järvenpää',
  'Kerava',
  'Kirkkonummi',
  'Nurmijärvi',
  'Tuusula',
  'Vihti',
  'Mäntsälä',
  'Sipoo',
  'Raasepori',
  'Hanko',
  'Karkkila',
];

export const _citiesFinlandArea2 = [
  'Turku',
  'Salo',
  'Kaarina',
  'Raisio',
  'Naantali',
  'Parainen',
  'Uusikaupunki',
  'Loimaa',
  'Paimio',
  'Lieto',
  'Auranmaa',
  'Kemiönsaari',
  'Laitila',
  'Somero',
  'Masku',
  'Nousiainen',
  'Rusko',
  'Sauvo',
  'Marttila',
  'Mynämäki',
  'Taivassalo',
  'Vehmaa',
  'Kustavi',
  'Pyhäranta',
];

export const _citiesFinlandArea3 = [
  'Tampere',
  'Nokia',
  'Ylöjärvi',
  'Kangasala',
  'Lempäälä',
  'Pirkkala',
  'Sastamala',
  'Valkeakoski',
  'Akaa',
  'Orivesi',
  'Mänttä-Vilppula',
  'Ikaalinen',
  'Parkano',
  'Virrat',
  'Ruovesi',
  'Kihniö',
  'Hämeenkyrö',
  'Vesilahti',
  'Pälkäne',
  'Juupajoki',
];

export const _citiesFinlandArea4 = [
  'Jyväskylä',
  'Äänekoski',
  'Jämsä',
  'Saarijärvi',
  'Keuruu',
  'Viitasaari',
  'Laukaa',
  'Muurame',
  'Petäjävesi',
  'Uurainen',
  'Toivakka',
  'Kannonkoski',
  'Karstula',
  'Kivijärvi',
  'Kyyjärvi',
  'Multia',
  'Pihtipudas',
  'Konnevesi',
  'Luhanka',
  'Hankasalmi',
  'Joutsa',
  'Leivonmäki',
];

export const _citiesFinlandArea5 = [
  'Lahti',
  'Heinola',
  'Hollola',
  'Orimattila',
  'Asikkala',
  'Kärkölä',
  'Padasjoki',
  'Nastola',
  'Sysmä',
  'Hartola',
];

export const _citiesSpainArea1 = [
  'Málaga',
  'Marbella',
  'Fuengirola',
  'Torremolinos',
  'Benalmádena',
  'Estepona',
  'Mijas',
  'Nerja',
  'Rincón de la Victoria',
  'Vélez-Málaga',
  'Manilva',
  'Casares',
];

// ----------------------------------------------------------------------

export const _tags = [
  `Ikkunanpesu`,
  `Kiinteistöhuolto`,
  `Remontit`,
  `Pihan muutos- ja rakennustyöt`,
  `Remontit`,
  `Rakentaminen`,
];

// ----------------------------------------------------------------------

export const _fullNames = [
  'Sabrina',
  'Sari',
  'Jaana',
  'Eija',
  'Hanna',
  'Heidi',
  'Sami',
  'Sirkka',
  'Toni',
  'Roosa',
  'Kenan',
  'Pekka',
  'Jani',
  'Aleksi',
  'Kirsti',
  'Malieha',
  'Tuomo',
  'Nina',
  'Carolina',
  'Katja',
  'Lotta',
  'Anneli',
  'Alexander',
  'Anne',
];

export const _firstNames = [
  'Sabrina',
  'Sari',
  'Jaana',
  'Eija',
  'Hanna',
  'Heidi',
  'Sami',
  'Sirkka',
  'Toni',
  'Roosa',
  'Kenan',
  'Pekka',
  'Jani',
  'Aleksi',
  'Kirsti',
  'Malieha',
  'Tuomo',
  'Nina',
  'Carolina',
  'Katja',
  'Lotta',
  'Anneli',
  'Alexander',
  'Anne',
];

export const _lastNames = [
  'Carroll',
  'Simonis',
  'Yost',
  'Hand',
  'Emmerich',
  'Wilderman',
  'Howell',
  'Sporer',
  'Boehm',
  'Morar',
  'Koch',
  'Reynolds',
  'Padberg',
  'Watsica',
  'Upton',
  'Yundt',
  'Pfeffer',
  'Parker',
  'Zulauf',
  'Treutel',
  'McDermott',
  'McDermott',
  'Cruickshank',
  'Parisian',
];

// ----------------------------------------------------------------------

export const _prices = [
  69, 199, 44, 44, 44, 44, 44, 59, 39, 69, 69, 54, 69, 44, 59, 69, 44, 74, 56, 56, 56, 44,
];

export const _ratings = [
  5.0, 4.8, 4.7, 5.0, 4.6, 5.0, 5.0, 4.4, 5.0, 5.0, 4.7, 4.3, 4.5, 4.2, 5.0, 4.9, 5.0, 4.6, 4.4,
  5.0, 4.9, 4.7, 4.8, 5.0,
];

// ----------------------------------------------------------------------

export const _serviceNames = [
  'Ilmastointityöt',
  'Asbestikartoitus',
  'Kotisiivous',
  'Muuttosiivous',
  'Toimistosiivous',
  'Remonttisiivous',
  'Ikkunanpesu',
  'Kuljetuspalvelut',
  'Kotiapu',
  'Sähköasennukset',
  'Elektroniikkahuolto',
  'Asennuspalvelut',
  'Kodinkonehuolto',
  'Kantoapu',
  'Muutto',
  'Putkityöt',
  'Kiinteistöhuolto ja isännöintipalvelut',
  'Kylmälaitteiden asennus',
  'Remontit ja rakentaminen',
  'Pihan muutos- ja rakennustyöt',
  'Pihatyöt',
  'Etsitkö muuta palvelua?',
];

// ----------------------------------------------------------------------

export const _serviceSlug = [
  'ilmastointityot',
  'asbestikartoitus',
  'kotisiivous',
  'muuttosiivous',
  'toimistosiivous',
  'remonttisiivous',
  'ikkunanpesu',
  'kuljetuspalvelut',
  'kotiapu',
  'sahkoasennukset',
  'elektroniikkahuolto',
  'asennuspalvelut',
  'kodinkonehuolto',
  'kantoapu',
  'muutto',
  'putkityot',
  'kiinteistohuolto',
  'kylmalaitteiden-asennus',
  'remontti',
  'piha-rakentaminen',
  'pihatyot',
  'koti-palvelu',
];

// ----------------------------------------------------------------------

export const _stripePaymentLink = [
  { value: 'https://book.stripe.com/fZeaIieNVeMd9q09G2', label: 'Ilmastointityöt 69€/h' },
  { value: 'https://book.stripe.com/9AQbMmgW36fHdGgaK7', label: 'Asbestikartoitus 199€/h' },
  { value: 'https://book.stripe.com/00geYy5dleMd45G3hG', label: 'Kotisiivous 44€/h' },
  { value: 'https://book.stripe.com/fZe7w69tB5bD31C07u', label: 'Kotisiivous 44€/h (Allergia siivous)' },
  { value: 'https://book.stripe.com/8wM5nY35ddI945G4nL', label: 'Kotisiivous 44€/h (Raivaussiivous)' },
  { value: 'https://book.stripe.com/28o8AaeNV5bD1XycUi', label: 'Kotisiivous 48€/h (lattian vahaus)' },
  { value: 'https://book.stripe.com/28o17IeNV47zfOo7zV', label: 'Kotisiivous 48€/h (Allergia siivous tai Lattian vahaus tai Raivaussiivous)' },
  { value: 'https://book.stripe.com/8wM4jU49h8nPdGg5pP', label: 'Muuttosiivous 44€/h' },
  { value: 'https://book.stripe.com/fZe17I6hp5bDau48E4', label: 'Muuttosiivous 44€/h (Allergia siivous)' },
  { value: 'https://book.stripe.com/28obMm9tB8nP1Xy5rT', label: 'Muuttosiivous 44€/h (Raivaussiivous)' },
  { value: 'https://book.stripe.com/eVa8AadJR6fHeKk4nQ', label: 'Muuttosiivous 48€/h (lattian vahaus)' },
  { value: 'https://book.stripe.com/6oE4jU0X5gUl1XyaMb', label: 'Muuttosiivous 48€/h (Allergia siivous tai Lattian vahaus tai Raivaussiivous)' },
  { value: 'https://book.stripe.com/3cs17I6hp47z8lWg4u', label: 'Toimistosiivous 44€/h' },
  { value: 'https://book.stripe.com/fZe2bMdJRdI97hS8E8', label: 'Toimistosiivous 44€/h (Allergia siivous)' },
  { value: 'https://book.stripe.com/5kA03E8px1ZrgSsf2x', label: 'Toimistosiivous 44€/h (Raivaussiivous)' },
  { value: 'https://book.stripe.com/3csg2CdJR47z59KcUq', label: 'Toimistosiivous 48€/h (lattian vahaus)' },
  { value: 'https://book.stripe.com/bIY7w67lt9rT31C1bF', label: 'Toimistosiivous 48€/h (Allergia siivous tai Lattian vahaus tai Raivaussiivous)' },
  { value: 'https://book.stripe.com/7sIbMm49h0Vn59Kf0r', label: 'Remonttisiivous 44€/h' },
  { value: 'https://book.stripe.com/eVa9Ee49h0VneKk4nW', label: 'Remonttisiivous 44€/h (Allergia siivous)' },
  { value: 'https://book.stripe.com/00g4jU5dlbA1au4aMl', label: 'Remonttisiivous 44€/h (Raivaussiivous)' },
  { value: 'https://book.stripe.com/6oE7w6gW3cE5fOo8Ee', label: 'Remonttisiivous 48€/h (lattian vahaus)' },
  { value: 'https://book.stripe.com/fZe7w6bBJ5bD1Xy2fN', label: 'Remonttisiivous 48€/h (Allergia siivous tai Lattian vahaus tai Raivaussiivous)' },
  { value: 'https://book.stripe.com/7sI5nY7lt33vdGgf0s', label: 'Ikkunanpesu 44€/h' },
  { value: 'https://book.stripe.com/6oEg2C9tB9rTby86tX', label: 'Kuljetuspalvelut 59€/h' },
  { value: 'https://book.stripe.com/7sI8Aa8px9rT7hScSm', label: 'Kotiapu 39€/h' },
  { value: 'https://book.stripe.com/8wM7w65dl0Vn9q09Gb', label: 'Sähköasennukset 69€/h' },
  { value: 'https://book.stripe.com/5kA5nY35d1Zr7hS6u2', label: 'Elektroniikkahuolto 69€/h' },
  { value: 'https://book.stripe.com/28obMm8px47z31C6u0', label: 'Asennuspalvelut 54€/h' },
  { value: 'https://book.stripe.com/bIY7w67lt6fH1Xyg4B', label: 'Kodinkonehuolto 69€/h' },
  { value: 'https://book.stripe.com/9AQ17IeNV6fH1Xy5pZ', label: 'Kantoapu 44€/h' },
  { value: 'https://book.stripe.com/aEU3fQaxF1Zr6dOf0A', label: 'Muutto 59€/h' },
  { value: 'https://book.stripe.com/14k3fQ0X5bA17hS05H', label: 'Putkityöt 69€/h' },
  {
    value: 'https://book.stripe.com/dR6dUu6hp0VneKk05I',
    label: 'Kiinteistöhuolto ja isännöintipalvelut 44€/h',
  },
  { value: 'https://book.stripe.com/4gweYybBJcE559K4lZ', label: 'Kylmälaitteiden asennus 74€/h' },
  { value: 'https://book.stripe.com/28o2bM9tB5bD8lW8Cg', label: 'Remontit ja rakentaminen 56€/h' },
  {
    value: 'https://book.stripe.com/4gwaIifRZ33vdGgbOt',
    label: 'Pihan muutos- ja rakennustyöt 56€/h',
  },
  { value: 'https://book.stripe.com/28odUu5dl47z59K9Gm', label: 'Pihatyöt 56€/h' },
  { value: 'https://www.hero24.com/koti-palvelu', label: 'Etsitkö muuta palvelua?' },
];

// ----------------------------------------------------------------------

export const _sentences = [
  'Kaikki meni erittäin hyvin. Muuttomiehet olivat asiantuntevia ja kaikki saatiin tehtyä suunnitellussa ajassa.',
  'Kiitos paljon teille ja pojat olivät ystävällisiä ja ahkerät annan 100 piste',
  'Job went smooth and finished in the given time frame',
  'Olin hyvin tyytyväinen Varmalta saamaani palveluun, työ hoidettiin ammattitaitoisesti ja ystävällisesti ja esitettyjen toiveiden mukaisesti.',
  'Täysi 10. Maalarimme (Ahonen) teki mitä sovittin. Työn laatu erinomainen. Tehtyään työnsä korjasi roskat ja siivosi jälkensä. Täydellistä. Kiitos. Raija Koivisto',
  'Hyvä siivous homma, tosi hyvä kommunikoimaan vastasi kaikkiin kysymyksiin nopeasti. Suosittelen kaikille!',
  'Very friendly and took quickly in contact with me. Cleaned fast and with attention to detail! I recommend! ',
  'Great experience, good communication about the process and very happy with the results of the paint job.',
  'Hei, aivan loistavaa palvelua, taitava sähkömies, luotettava, asiantuntema ja erittäin hyvä asiakaspalvelu. Sain todella paljon apua neljän tunnin työn aikana ja kaikki tarvitsemat sähkötyöt tuli tehtyä ripeästi, siististi ja turvallisesti. Iso kiitos hänelle!',
  'Pesukoneen asennus sujui erittäin hyvin ja ammattitaitoisesti. Asentaja oli todella tarkka työstään ja ystävällinen.',
  'Todella hyvää työtä. Homma hoitui kätevästi ja työn jälki mahtavaa! Kiitos!',
  'Laadukasta asiakaspalvelua, asentaja piti ajantasalla milloin on tulossa ja sai työn tehtyä ajallaan.',
  'Niko hoito homma erittäin hyvin ja ammattimaisesti. Iso suositus kaikille jos haluaa osaavan kaverin',
  'Mukava ja ammattitaitoinen asentaja. Joutui tulemaan toiste, kun pyykinpesukoneen poistoputki ei asennuksen jälkeen ollutkaan riittävän tiukalla, vaan vedet tulivat putken ulkopuolelle. Toinen käynti järjestyi jo samalle päivälle ja homma saatiin kuntoon. Oppimiskäynti asentajallekin, kuten myös asiakkaalle, kannattaa tehdä testihuuhtelu ja testityhjennys ennen asennuskäynniltä poistumista.',
  'Hienosti toimi sovitusti. Minun puhelimessa tämä applikaatio ei valitettavasti toimi kunnolla esin kuvien lisäämisen suhteen. Tämä puhelin One plus nord ja tällä mallilla ongelmia myös muiden sovellusten toimivuuden kanssa.',
];

// ----------------------------------------------------------------------

export const _serviceSentences1 = [
  'Ilmanvaihtojärjestelmien asennus: Asennamme uudet ilmanvaihtojärjestelmät ammattitaitoisesti.',
  'Asbestikartoitukset: Teemme perusteellisen kartoituksen rakennuksesi asbestipitoisista materiaaleista.',
  'Kotisiivous: Perusteellinen ja säännöllinen siivous kotonasi.',
  'Perusteellinen siivous: Puhdistamme kodin lattiasta kattoon.',
  'Kotisiivous: Perusteellinen ja säännöllinen siivous kotonasi.',
  'Kotisiivous: Perusteellinen ja säännöllinen siivous kotonasi.',
  'Perusteellinen ikkunanpesu: Puhdistamme ikkunat sisä- ja ulkopuolelta.',
  'Muutto- ja kuljetuspalvelut: Hoidamme muutot ja tavaroiden kuljetukset ammattitaidolla.',
  'Kotisiivous: Perusteellinen viikkosiivous, ikkunanpesu ja erikoissiivoukset.',
  'Sähköasennukset ja -korjaukset: Ammattitaitoinen tiimimme hoitaa kaikki sähkötyöt laadukkaasti ja turvallisesti.',
  'Laitteiden vianmääritys ja korjaus: Korjaamme rikkoutuneet elektroniikkalaitteet nopeasti ja tehokkaasti.',
  'Pienet korjaustyöt: Kodin ja toimitilan pienet korjaustyöt.',
  'Vianmääritys ja korjaus: Korjaamme rikkoutuneet kodinkoneet nopeasti ja tehokkaasti.',
  'Huonekalujen ja kodinkoneiden kantoapu: Siirrämme raskaat esineet ammattitaidolla.',
  'Muuttopalvelut: Hoidamme muutot ammattitaidolla ja tehokkaasti.',
  'Putkiasennukset ja -korjaukset: Ammattitaitoinen tiimimme hoitaa kaikki putkityöt laadukkaasti ja turvallisesti.',
  'Ylläpitohuolto: Säännöllinen kiinteistönhuolto, joka pitää kiinteistön toimivana.',
  'Kylmälaitteiden asennus: Asennamme jääkaapit, pakastimet ja muut kylmälaitteet ammattitaidolla.',
  'Keittiö- ja kylpyhuoneremontit: Toteutamme unelmiesi keittiön ja kylpyhuoneen.',
  'Pihan suunnittelu ja rakentaminen: Toteutamme pihasi unelmat alusta loppuun.',
  'Nurmikon leikkaus: Pidämme nurmikkosi siistinä ja hyvinvoivana.',
  'Meiltä löytyy laaja valikoima eri palveluita.',
];

// ----------------------------------------------------------------------

export const _serviceSentences2 = [
  'Ilmanvaihtojärjestelmien huolto: Säännöllinen huolto varmistaa järjestelmän tehokkaan toiminnan.',
  'Näytteiden analysointi: Analysoimme näytteet laboratoriossa luotettavien tulosten saamiseksi.',
  'Ikkunanpesu: Ammattitaitoinen ja tarkka ikkunoiden pesu.',
  'Ikkunanpesu: Pesemme ikkunat kirkkaiksi.',
  'Ikkunanpesu: Ammattitaitoinen ja tarkka ikkunoiden pesu.',
  'Ikkunanpesu: Ammattitaitoinen ja tarkka ikkunoiden pesu.',
  'Kehysten ja karmin puhdistus: Huolehdimme myös ikkunoiden kehyksistä ja karmeista.',
  'Erikoiskuljetukset: Kuljetamme herkkää ja arvokasta tavaraa turvallisesti.',
  'Pienet korjaustyöt: Kodinkoneiden korjaukset, huonekalujen korjaukset ja pienet remontit.',
  'Vikadiagnostiikka ja korjaukset: Selvitä ja korjaa sähkölaitteiden viat nopeasti.',
  'Huolto ja ylläpito: Tarjoamme säännöllistä huoltoa laitteiden pitkän käyttöiän varmistamiseksi.',
  'Kalusteiden kokoaminen: Kalusteiden kokoaminen ja asennus.',
  'Säännöllinen huolto: Tarjoamme säännöllistä huoltoa laitteiden pitkän käyttöiän varmistamiseksi.',
  'Muuttoapu: Avustamme muutossa, jotta raskaat tavarat siirtyvät turvallisesti.',
  'Pakkauspalvelut: Pakkaamme tavarasi huolellisesti ja turvallisesti.',
  'Vuototarkistukset ja korjaukset: Selvitämme ja korjaamme vuotavat putket nopeasti.',
  'LVI-työt: Lämpö-, vesi- ja ilmanvaihtojärjestelmien huolto ja korjaus.',
  'Kylmälaitteiden huolto: Säännöllinen huolto takaa laitteiden pitkän käyttöiän.',
  'Lattia- ja seinäremontit: Uudistamme lattiat ja seinät ammattitaidolla.',
  'Kiveykset ja terassit: Asennamme pihalaatat, kivet ja terassit.',
  'Pensasaidan leikkaus: Muotoilemme ja hoidamme pensasaidat ammattitaidolla.',
  'Täytä lomake ja kerro tarpeesi',
];

// ----------------------------------------------------------------------

export const _serviceSentences3 = [
  'Kanavien puhdistus: Puhdistamme ilmanvaihtokanavat perusteellisesti.',
  'Raportointi ja suositukset: Toimitamme kattavan raportin ja suositukset jatkotoimenpiteistä.',
  'Erikoissiivoukset: Muutot, remontit ja muut erityistilanteet.',
  'Erikoispuhdistukset: Hoidamme erityistä huolellisuutta vaativat kohteet.',
  'Erikoissiivoukset: Muutot, remontit ja muut erityistilanteet.',
  'Erikoissiivoukset: Muutot, remontit ja muut erityistilanteet.',
  'Erikoispuhdistukset: Hoidamme herkkien ja vaikeasti saavutettavien ikkunoiden pesut.',
  'Logistiikkaratkaisut: Räätälöimme kuljetuspalvelut tarpeidesi mukaan.',
  'Kotiapu arjen askareissa: Autamme ruoanlaitossa, pyykinpesussa ja muissa arjen askareissa.',
  'Pistorasioiden ja valaisimien asennus: Asennamme ja vaihdamme pistorasiat ja valaisimet.',
  'Päivitykset ja asennukset: Asennamme ja päivitämme ohjelmistot ja laitteistot tarpeidesi mukaan.',
  'Maalaus- ja tapetointityöt: Seinien ja kattojen maalaus sekä tapetointi.',
  'Asennus ja päivitykset: Asennamme uudet kodinkoneet ja päivitämme vanhat laitteet.',
  'Erikoisesineiden kanto: Hoidamme herkkien ja arvokkaiden esineiden siirrot.',
  'Kuljetuspalvelut: Kuljetamme tavarasi uuteen kotiin turvallisesti ja ajallaan.',
  'Lämmitysjärjestelmien asennus ja huolto: Asennamme ja huollamme lämmitysjärjestelmät tehokkaasti.',
  'Talotekniikan huolto: Sähköjärjestelmien ja muiden teknisten laitteiden ylläpito.',
  'Vikakorjaukset: Korjaamme nopeasti ja tehokkaasti kaikki kylmälaitteiden viat.',
  'Muut remonttipalvelut: Kaikki pienet ja suuret remontit tarpeidesi mukaan.',
  'Istutukset ja viheralueet: Suunnittelemme ja toteutamme istutukset ja viheralueet.',
  'Syksyn lehdenpoisto: Puhdistamme pihasi syksyn lehdistä nopeasti ja tehokkaasti.',
  'Niin autamme sinua löytämään sen!',
];

// ----------------------------------------------------------------------

export const _reasons1 = [
  'Kokeneet ammattilaiset: Varmistamme korkealaatuisen ja turvallisen työn.',
  'Kokeneet ammattilaiset: Varmistamme tarkat ja luotettavat tulokset.',
  'Kokeneet siivoojat: Varmistamme korkealaatuisen ja huolellisen työn.',
  'Kokeneet siivoojat: Varmistamme korkealaatuisen ja huolellisen työn.',
  'Kokeneet siivoojat: Varmistamme korkealaatuisen ja huolellisen työn.',
  'Kokeneet siivoojat: Varmistamme korkealaatuisen ja huolellisen työn.',
  'Kokeneet ammattilaiset: Varmistamme korkealaatuisen ja huolellisen työn.',
  'Kokeneet ammattilaiset: Varmistamme turvallisen ja tehokkaan kuljetuksen.',
  'Kokeneet ammattilaiset: Varmistamme korkealaatuisen ja huolellisen työn.',
  'Kokeneet sähköasentajat: Varmistamme korkealaatuisen ja turvallisen työn.',
  'Kokeneet ammattilaiset: Varmistamme korkealaatuisen ja luotettavan työn.',
  'Kokeneet ammattilaiset: Varmistamme korkealaatuisen ja turvallisen työn.',
  'Kokeneet ammattilaiset: Varmistamme korkealaatuisen ja luotettavan työn.',
  'Kokeneet ammattilaiset: Varmistamme turvallisen ja tehokkaan työn.',
  'Kokeneet muuttomiehet: Varmistamme korkealaatuisen ja turvallisen muuton.',
  'Kokeneet putkiasentajat: Varmistamme korkealaatuisen ja turvallisen työn.',
  'Kokeneet kiinteistönhoitajat: Varmistamme korkealaatuisen ja huolellisen työn.',
  'Kokeneet ammattilaiset: Varmistamme korkealaatuisen ja turvallisen työn.',
  'Kokeneet ammattilaiset: Varmistamme korkealaatuisen ja turvallisen työn.',
  'Kokeneet ammattilaiset: Varmistamme korkealaatuisen ja kestävän työn.',
  'Kokeneet pihatyöntekijät: Varmistamme korkealaatuisen ja huolellisen työn.',
  'Meiltä löytyy laaja valikoima eri palveluita.',
];

// ----------------------------------------------------------------------

export const _reasons2 = [
  'Nopea ja luotettava palvelu: Reagoimme nopeasti ja hoidamme työn tehokkaasti.',
  'Nopea ja luotettava palvelu: Reagoimme nopeasti ja hoidamme työn tehokkaasti.',
  'Nopea ja luotettava palvelu: Reagoimme nopeasti ja hoidamme työn tehokkaasti.',
  'Nopea ja luotettava palvelu: Reagoimme nopeasti ja hoidamme työn tehokkaasti.',
  'Nopea ja luotettava palvelu: Reagoimme nopeasti ja hoidamme työn tehokkaasti.',
  'Nopea ja luotettava palvelu: Reagoimme nopeasti ja hoidamme työn tehokkaasti.',
  'Nopea ja luotettava palvelu: Reagoimme nopeasti ja hoidamme työn tehokkaasti.',
  'Nopea ja luotettava palvelu: Reagoimme nopeasti ja hoidamme työn huolellisesti.',
  'Nopea ja luotettava palvelu: Reagoimme nopeasti ja hoidamme työn tehokkaasti.',
  'Nopea ja luotettava palvelu: Reagoimme nopeasti ja hoidamme työn tehokkaasti.',
  'Nopea ja luotettava palvelu: Reagoimme nopeasti ja hoidamme työn tehokkaasti.',
  'Nopea ja luotettava palvelu: Reagoimme nopeasti ja hoidamme työn tehokkaasti.',
  'Nopea ja luotettava palvelu: Reagoimme nopeasti ja hoidamme työn tehokkaasti.',
  'Nopea ja luotettava palvelu: Reagoimme nopeasti ja hoidamme työn huolellisesti.',
  'Nopea ja luotettava palvelu: Reagoimme nopeasti ja hoidamme työn tehokkaasti.',
  'Nopea ja luotettava palvelu: Reagoimme nopeasti ja hoidamme työn tehokkaasti.',
  'Nopea ja luotettava palvelu: Reagoimme nopeasti ja hoidamme työn tehokkaasti.',
  'Nopea ja luotettava palvelu: Reagoimme nopeasti ja hoidamme työn tehokkaasti.',
  'Nopea ja luotettava palvelu: Reagoimme nopeasti ja hoidamme työn tehokkaasti.',
  'Nopea ja luotettava palvelu: Reagoimme nopeasti ja hoidamme työn tehokkaasti.',
  'Nopea ja luotettava palvelu: Reagoimme nopeasti ja hoidamme työn tehokkaasti.',
  'Täytä lomake ja kerro tarpeesi',
];

// ----------------------------------------------------------------------

export const _reasons3 = [
  'Asiakastyytyväisyys: Tyytyväiset asiakkaat ovat toimintamme perusta.',
  'Asiakastyytyväisyys: Tyytyväiset asiakkaat ovat toimintamme perusta.',
  'Asiakastyytyväisyys: Tyytyväiset asiakkaat ovat toimintamme perusta.',
  'Asiakastyytyväisyys: Tyytyväiset asiakkaat ovat toimintamme perusta.',
  'Asiakastyytyväisyys: Tyytyväiset asiakkaat ovat toimintamme perusta.',
  'Asiakastyytyväisyys: Tyytyväiset asiakkaat ovat toimintamme perusta.',
  'Asiakastyytyväisyys: Tyytyväiset asiakkaat ovat toimintamme perusta.',
  'Asiakastyytyväisyys: Tyytyväiset asiakkaat ovat toimintamme perusta.',
  'Asiakastyytyväisyys: Tyytyväiset asiakkaat ovat toimintamme perusta.',
  'Asiakastyytyväisyys: Tyytyväiset asiakkaat ovat toimintamme perusta.',
  'Asiakastyytyväisyys: Tyytyväiset asiakkaat ovat toimintamme perusta.',
  'Asiakastyytyväisyys: Tyytyväiset asiakkaat ovat toimintamme perusta.',
  'Asiakastyytyväisyys: Tyytyväiset asiakkaat ovat toimintamme perusta.',
  'Asiakastyytyväisyys: Tyytyväiset asiakkaat ovat toimintamme perusta.',
  'Asiakastyytyväisyys: Tyytyväiset asiakkaat ovat toimintamme perusta.',
  'Asiakastyytyväisyys: Tyytyväiset asiakkaat ovat toimintamme perusta.',
  'Asiakastyytyväisyys: Tyytyväiset asiakkaat ovat toimintamme perusta.',
  'Asiakastyytyväisyys: Tyytyväiset asiakkaat ovat toimintamme perusta.',
  'Asiakastyytyväisyys: Tyytyväiset asiakkaat ovat toimintamme perusta.',
  'Asiakastyytyväisyys: Tyytyväiset asiakkaat ovat toimintamme perusta.',
  'Asiakastyytyväisyys: Tyytyväiset asiakkaat ovat toimintamme perusta.',
  'Niin autamme sinua löytämään sen!',
];

// ----------------------------------------------------------------------

export const _descriptions = [
  'Tarjoamme kattavia ja luotettavia ilmanvaihtojärjestelmien asennus- ja huoltopalveluja, jotta kotisi ilma pysyy raikkaana ja terveellisenä. Asiantuntevat ammattilaisemme hoitavat kaiken tarvittavan, jotta sinä voit nauttia puhtaasta sisäilmasta.',
  'Tarjoamme kattavia ja luotettavia asbestikartoituspalveluja, jotta voit varmistaa tilojesi turvallisuuden. Asiantuntevat ammattilaisemme hoitavat kaiken tarvittavan, jotta sinä voit olla huoletta asbestin suhteen.',
  'Tarjoamme kattavia ja luotettavia siivouspalveluja, jotta kotisi pysyy puhtaana ja viihtyisänä. Asiantuntevat siivoojamme hoitavat kaiken tarvittavan, jotta sinä voit keskittyä muihin tärkeisiin asioihin.',
  'Tarjoamme kattavia ja luotettavia siivouspalveluja, jotka tekevät muuttamisesta helppoa ja stressitöntä. Asiantuntevat siivoojamme huolehtivat, että vanha ja uusi koti ovat moitteettoman puhtaita.',
  'Tarjoamme kattavia ja luotettavia siivouspalveluja, jotta kotisi pysyy puhtaana ja viihtyisänä. Asiantuntevat siivoojamme hoitavat kaiken tarvittavan, jotta sinä voit keskittyä muihin tärkeisiin asioihin.',
  'Tarjoamme kattavia ja luotettavia siivouspalveluja, jotta kotisi pysyy puhtaana ja viihtyisänä. Asiantuntevat siivoojamme hoitavat kaiken tarvittavan, jotta sinä voit keskittyä muihin tärkeisiin asioihin.',
  'Tarjoamme kattavia ja luotettavia ikkunanpesupalveluja, jotta kotisi ja toimitilasi ikkunat pysyvät kirkkaan puhtaina. Asiantuntevat pesijämme hoitavat kaiken tarvittavan, jotta sinä voit nauttia kirkkaista näkymistä.',
  'kuljetuspalveluiden sivulle! Tarjoamme kattavia ja luotettavia kuljetuspalveluja, jotta tavarasi liikkuvat turvallisesti ja ajallaan. Asiantuntevat kuljettajamme hoitavat kaiken tarvittavan, jotta sinä voit keskittyä muihin asioihin.',
  'Tarjoamme kattavia ja luotettavia kotiavun palveluja, jotka helpottavat arkeasi ja tekevät kodistasi viihtyisämmän. Asiantuntevat työntekijämme hoitavat kaiken tarvittavan, jotta sinä voit keskittyä muihin asioihin.',
  'Tarjoamme monipuolisia ja luotettavia sähköasennuspalveluja varmistaaksemme kotisi turvallisuuden ja toimivuuden. Asiantuntevat sähköasentajamme hoitavat kaiken tarvittavan, jotta sinä voit keskittyä muihin tärkeisiin asioihin.',
  'Tarjoamme kattavia ja luotettavia elektroniikkahuoltopalveluja, jotta laitteesi toimivat moitteettomasti. Asiantuntevat teknikkömme hoitavat kaiken tarvittavan, jotta sinä voit nauttia toimivista laitteista ilman huolta.',
  'Tarjoamme monipuolisia ja luotettavia asennuspalveluja, jotka kattavat kodin ja toimitilan pienet ja suuret kunnostustyöt. Asiantuntevat ammattilaisemme hoitavat kaiken tarvittavan, jotta sinä voit keskittyä muihin asioihin.',
  'Tarjoamme kattavia ja luotettavia kodinkonehuoltopalveluja, jotta kodinkoneesi toimivat moitteettomasti. Asiantuntevat teknikkömme hoitavat kaiken tarvittavan, jotta sinä voit nauttia toimivista laitteista ilman huolta.',
  'Kantoavun palveluiden sivulle! Tarjoamme kattavia ja luotettavia kantoapupalveluja, jotta raskaat ja hankalat esineet siirtyvät vaivattomasti. Asiantuntevat kantajamme hoitavat kaiken tarvittavan, jotta sinä voit keskittyä muihin asioihin.',
  'Tarjoamme kattavia ja luotettavia muuttopalveluja varmistaaksemme sujuvan muuton ilman stressiä. Asiantuntevat muuttomiehemme hoitavat kaiken tarvittavan, jotta sinä voit keskittyä uuteen kotiisi.',
  'Tarjoamme kattavia ja luotettavia putkiasennus- ja korjauspalveluja varmistaaksemme kotisi putkijärjestelmien moitteettoman toiminnan. Asiantuntevat putkimiehemme hoitavat kaikki tarvittavat toimenpiteet, jotta sinä voit huoletta nauttia arjestasi.',
  'Tarjoamme kattavia ja luotettavia kiinteistönhoitopalveluja, jotta kiinteistösi pysyy kunnossa ja toimivana ympäri vuoden. Asiantuntevat ammattilaisemme hoitavat kaikki kiinteistönhoidon tarpeesi, jotta sinä voit keskittyä muihin asioihin.',
  'Tarjoamme kattavia ja luotettavia kylmälaitteiden asennus- ja huoltopalveluja, jotta kodin ja yrityksen kylmälaitteet toimivat moitteettomasti. Asiantuntevat ammattilaisemme hoitavat kaiken tarvittavan, jotta sinä voit nauttia huolettomasta käytöstä.',
  'Tarjoamme kattavia ja luotettavia remonttipalveluja, jotta kotisi ja toimitilasi pysyvät parhaassa mahdollisessa kunnossa. Asiantuntevat ammattilaisemme hoitavat kaikki remonttitarpeesi, jotta sinä voit keskittyä muihin asioihin.',
  'Tarjoamme kattavia ja luotettavia pihan muutos- ja rakennuspalveluja, jotta pihasi näyttää juuri siltä kuin haluat. Asiantuntevat ammattilaisemme hoitavat kaiken tarvittavan, jotta sinä voit nauttia kauniista ja toimivasta pihasta.',
  'Tarjoamme kattavia ja luotettavia pihatöitä, jotta pihasi pysyy siistinä ja viihtyisänä ympäri vuoden. Asiantuntevat ammattilaisemme hoitavat kaiken tarvittavan, jotta sinä voit nauttia kauniista pihasta ilman vaivaa.',
  'Etsitkö muuta palvelua? Meiltä löytyy laaja valikoima eri palveluita. Täytä lomake ja kerro tarpeesi, niin autamme sinua löytämään sen!',
];

// ----------------------------------------------------------------------

export const _feedback = [
  '',
  'Julia pyysi tarjousta terassin rakentamisesta, ja sovimme arviokäynnin samalle viikolle. Hän sai nopeasti budjettiinsa sopivan tarjouksen, jonka hyväksyi. Sankari rakensi terassin ripeästi ja tarkasti. Julia kommentoi: "Ammattimaista työtä, ystävällinen henkilökunta. Sujuva palvelu, kiitos! Suosittelen vahvasti!"',
  '',
  '',
  'Kohde vaikutti ensiksi hieman hankalalta mutta saatin asiakkaan kanssa yhdessä tehty hyvät työsuunnitelmat ja sitä myöten myös lopputulos oli erittäin hieno. Omalla tavalla erityistä tässä oli tosiaan tuo asia että kyseinen huone on ollu vaille lopputöitä pitkään aika ja nyt se saatin kuntoon, siitä asiakas oli eritystukisopimuksissa kiitollinen.',
];
